import ev1 from "../../../public/images/ev1.jpg";
import ev2 from "../../../public/images/ev2.jpg";
import ev3 from "../../../public/images/ev3.jpg";
import ev4 from "../../../public/images/ev4.jpg";

export const houseData = [
  {
    id: 1,
    price: "5,970",
    title: "Tranquil Haven",
    type: "enSon",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 4,
    floor: "3/12",
    field: "120 m2",
    metro: "N.Nərimanov",
    time: "20 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 2,
    price: "2,850",
    title: "Lakeview Cozy Apartment",
    type: "enSon",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 2,
    floor: "2/10",
    field: "85 m2",
    metro: "Gənclik",
    time: "15 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 3,
    price: "3,200",
    title: "Modern City Loft",
    type: "enSon",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 3,
    floor: "5/9",
    field: "100 m2",
    metro: "28 May",
    time: "10 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 4,
    price: "3,750",
    title: "Elegant Park Residence",
    type: "enSon",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 4,
    floor: "7/12",
    field: "130 m2",
    metro: "Elmlər Akademiyası",
    time: "12 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 5,
    price: "2,600",
    title: "Sunset Studio",
    type: "enSon",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 1,
    floor: "1/5",
    field: "60 m2",
    metro: "Xətai",
    time: "18 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 6,
    price: "4,100",
    title: "High Rise Comfort",
    type: "enSon",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 3,
    floor: "10/15",
    field: "110 m2",
    metro: "İçərişəhər",
    time: "8 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },

  // Popular elanlar
  {
    id: 7,
    price: "1,970",
    title: "Suburban Comfort Home",
    type: "popular",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 4,
    floor: "3/12",
    field: "120 m2",
    metro: "N.Nərimanov",
    time: "20 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 8,
    price: "2,400",
    title: "Peaceful Retreat",
    type: "popular",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 3,
    floor: "4/10",
    field: "95 m2",
    metro: "Gənclik",
    time: "16 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 9,
    price: "3,800",
    title: "City Center Flat",
    type: "popular",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 2,
    floor: "6/12",
    field: "90 m2",
    metro: "28 May",
    time: "10 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 10,
    price: "4,250",
    title: "Bright Modern House",
    type: "popular",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 4,
    floor: "2/8",
    field: "140 m2",
    metro: "Sahil",
    time: "13 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 11,
    price: "3,150",
    title: "Luxury Midtown Home",
    type: "popular",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 3,
    floor: "9/14",
    field: "125 m2",
    metro: "Neftçilər",
    time: "22 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 12,
    price: "2,950",
    title: "Quiet Garden Apartment",
    type: "popular",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 2,
    floor: "3/6",
    field: "85 m2",
    metro: "Memar Əcəmi",
    time: "19 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },

  // Endirimli elanlar
  {
    id: 13,
    price: "2,670",
    title: "Compact Cozy Home",
    type: "endirimli",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 3,
    floor: "3/12",
    field: "120 m2",
    metro: "N.Nərimanov",
    time: "20 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 14,
    price: "3,300",
    title: "Stylish Family Villa",
    type: "endirimli",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 4,
    floor: "2/10",
    field: "135 m2",
    metro: "Gənclik",
    time: "17 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 15,
    price: "2,980",
    title: "Simple Budget Apartment",
    type: "endirimli",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 2,
    floor: "1/5",
    field: "75 m2",
    metro: "Əhmədli",
    time: "25 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 16,
    price: "3,600",
    title: "Elegant Downtown Loft",
    type: "endirimli",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 3,
    floor: "5/8",
    field: "110 m2",
    metro: "Nizami",
    time: "12 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 17,
    price: "2,200",
    title: "Affordable Studio",
    type: "endirimli",
    location: "1964 Jehovah Drive, VA 22408",
    beds: 1,
    floor: "2/4",
    field: "55 m2",
    metro: "Nəsimi",
    time: "22 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 18,
    price: "3,500",
    title: "Modern Apartment",
    type: "populyar",
    location: "4538 Oak Street, NY 10001",
    beds: 2,
    floor: "5/9",
    field: "85 m2",
    metro: "28 May",
    time: "12 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 19,
    price: "1,800",
    title: "Cozy 1-Bedroom",
    type: "ən son",
    location: "2297 Elm Street, TX 75201",
    beds: 1,
    floor: "3/5",
    field: "60 m2",
    metro: "Gənclik",
    time: "18 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 20,
    price: "4,100",
    title: "Spacious Family Flat",
    type: "populyar",
    location: "1780 Maple Ave, IL 60016",
    beds: 3,
    floor: "7/10",
    field: "120 m2",
    metro: "Neftçilər",
    time: "15 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
  {
    id: 21,
    price: "2,750",
    title: "Bright & Airy Loft",
    type: "endirimli",
    location: "364 Pine Street, CA 94111",
    beds: 2,
    floor: "4/6",
    field: "78 m2",
    metro: "Əcəmi",
    time: "20 dəq", 
    images: [
      ev1.src,
      ev2.src,
      ev3.src,
      ev4.src,
    ],
  },
];
